version: '3.8'

services:
  redis:
    image: 'bitnami/redis:latest'
    container_name: dauth-redis
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save '' --appendonly no --loglevel warning --protected-mode no
    volumes:
      - cache:/data
volumes:
  cache:
    driver: local
