export class GithubProfileEntity {
  id!: string;
  nodeId!: string;
  displayName!: string;
  username!: string;
  profileUrl!: string;
  emails!: { value: string }[];
  photos!: { value: string }[];
  provider!: 'github';
  _raw!: string;
  _json!: {
    login: string;
    id: 5841530;
    node_id: string;
    avatar_url: string;
    gravatar_id: string;
    url: string;
    html_url: string;
    followers_url: string;
    following_url: string;
    gists_url: string;
    starred_url: string;
    subscriptions_url: string;
    organizations_url: string;
    repos_url: string;
    events_url: string;
    received_events_url: string;
    type: string;
    site_admin: false;
    name: string;
    company: string;
    blog: string;
    location: string;
    email: string;
    hireable: true;
    bio: string;
    twitter_username: null;
    public_repos: 38;
    public_gists: 0;
    followers: 8;
    following: 10;
    created_at: string;
    updated_at: string;
  };
}
